import { OnInit, EventEmitter, OnChanges, SimpleChanges } from '@angular/core';
import { ImageViewerConfig } from './models/image-viewer-config.model';
import { CustomImageEvent } from './models/custom-image-event-model';
import { CdkDrag } from '@angular/cdk/drag-drop';
import * as i0 from "@angular/core";
export declare class AngularImageViewerComponent implements OnInit, OnChanges {
    moduleConfig: ImageViewerConfig;
    cdkDrag: CdkDrag;
    src: string[];
    config: ImageViewerConfig;
    screenHeightOccupied: number;
    index: number;
    imageName: string;
    footerTexts: string[];
    indexChange: EventEmitter<number>;
    configChange: EventEmitter<ImageViewerConfig>;
    customImageEvent: EventEmitter<CustomImageEvent>;
    styleHeight: string;
    style: {
        transform: string;
        msTransform: string;
        oTransform: string;
        webkitTransform: string;
    };
    fullscreen: boolean;
    loading: boolean;
    isDragOn: boolean;
    private scale;
    private rotation;
    private hovered;
    constructor(moduleConfig: ImageViewerConfig);
    ngOnChanges(changes: SimpleChanges): void;
    ngOnInit(): void;
    nextImage(event: MouseEvent): void;
    prevImage(event: MouseEvent): void;
    zoomIn(): void;
    zoomOut(): void;
    scrollZoom(evt: WheelEvent): boolean;
    rotateClockwise(): void;
    rotateCounterClockwise(): void;
    onLoad(): void;
    onLoadStart(): void;
    imageNotFound(): void;
    onDragStart(evt: any): void;
    toggleFullscreen(): void;
    triggerIndexBinding(): void;
    triggerConfigBinding(): void;
    fireCustomEvent(name: string, imageIndex: number): void;
    reset(): void;
    onMouseOver(): void;
    onMouseLeave(): void;
    private canNavigate;
    private updateStyle;
    private mergeConfig;
    private unwrap;
    static ɵfac: i0.ɵɵFactoryDeclaration<AngularImageViewerComponent, [{ optional: true; }]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AngularImageViewerComponent, "angular-image-viewer", never, { "src": "src"; "config": "config"; "screenHeightOccupied": "screenHeightOccupied"; "index": "index"; "imageName": "imageName"; "footerTexts": "footerTexts"; }, { "indexChange": "indexChange"; "configChange": "configChange"; "customImageEvent": "customImageEvent"; }, never, never>;
}
